In [8]:
import numpy as np
data = np.random.randint(1, 10, [10, 3])
print(data)

[[4 9 3]
 [8 7 8]
 [4 5 8]
 [6 4 9]
 [4 9 5]
 [9 4 4]
 [3 1 6]
 [5 1 6]
 [1 4 6]
 [5 3 3]]


In [14]:
axis = 0 % data.shape[1]
print(axis)

0


In [18]:
data[:, axis]

array([4, 8, 4, 6, 4, 9, 3, 5, 1, 5])

In [17]:
data[:, axis].argsort()

array([8, 6, 0, 2, 4, 7, 9, 3, 1, 5], dtype=int64)

In [15]:
sorted_data = data[data[:, axis].argsort()]
print(sorted_data)

[[1 4 6]
 [3 1 6]
 [4 9 3]
 [4 5 8]
 [4 9 5]
 [5 1 6]
 [5 3 3]
 [6 4 9]
 [8 7 8]
 [9 4 4]]


In [20]:
median = len(sorted_data) // 2
print(median)

5


In [21]:
sorted_data[median]

array([5, 1, 6])